In this notebook we are going to cover some basic fundamentality of the tensorflow.

In [7]:
# Introduction to tensors
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.5.0


In [10]:
vector = tf.constant(np.array([[1, 2, 3], [4, 5, 6]]))
vector

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [11]:
vector.ndim

2

In [17]:
mat1 = tf.constant([[[1.,5.,6.],[4.,7.,8.],[11.,22.,33.]]], dtype= tf.float16)

In [18]:
mat1

<tf.Tensor: shape=(1, 3, 3), dtype=float16, numpy=
array([[[ 1.,  5.,  6.],
        [ 4.,  7.,  8.],
        [11., 22., 33.]]], dtype=float16)>

In [19]:
mat1.ndim

3

creating tensors with `tf.Variable`



In [20]:
ct = tf.Variable([10.,7.])

In [21]:
ct

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([10.,  7.], dtype=float32)>

In [22]:
ct[0].assign(4.)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([4., 7.], dtype=float32)>